version: '3'
services:
  mongo:
    container_name: mongo
    image: "mongo:4.0.0"
    ports:
      - "27017:27017"
    volumes: 
      - mongodata:/data/db
  
volumes:
  mongodata:
    name: mongodata
    
